namespace SpriteKind {
    export const Trash = SpriteKind.create()
    export const Teleporter = SpriteKind.create()
    export const Bush = SpriteKind.create()
}

scene.onOverlapTile(SpriteKind.Player, assets.tile`doorClosedEast`, function (sprite, location) {
    levelSwitch()
})

sprites.onCreated(SpriteKind.Bush, function (sprite) {
    dedBush = sprites.create(img`
        ................................
        ............f...................
        ............8f..8..f.......ff...
        ......f......8..f..f....fff.....
        .....8......f8..f.f....ff.......
        fff..8f.....f8..f.f...ff..ff....
        ...f8f8f....f8f..8....88...f....
        .....ff8f....ff..88..f8....8f...
        .......f88...fff.f8f.8f....ff...
        .......fffff..ff..ff.8f...88fff.
        .........ff8f.fff.ff88f..f8ff...
        ...........fffffff.f8f..ffff....
        ....88888f..ffffffffff.f8f......
        ...f....f8ff88fffff8fffff.......
        ...f......8fff88fffff88f........
        ..............f88fffffff........
        ...............88ffffff.........
        ...............f88ffff..........
        ................88ffff..........
        ................88fff...........
        ................88fff...........
        ................88fff...........
        ................88fff...........
        ................88fff...........
        ................88fff...........
        ...............f8ffff...........
        ...............88ffff...........
        ..............888fffff..........
        .............f8fffffff..........
        .........f88f88f.fffffff........
        ......8ff8f.fff..f8f.ff.ff......
        ....f8f....f......f...fff.ffff..
        `, SpriteKind.Bush)
    dedBush.setPosition(randint(0, 190), randint(0, 190))
})

const trashSprites = [img`
................................
................................
................................
.............8888...............
.............8888...............
.............8888...............
.............88889..............
............9999999.............

............9999999.............
............9999999.............
............9999999.............
............9666669.............
............9611169.............
...........99611169.............
..........9996666699............
..........9999999999............
..........9999999699............
..........9999999699............
..........9999999699............
..........9999999699............
..........9999999999............
..........9999999999............
..........9999999999............
..........9999999999............
..........9999999999............
..........9999999999............
..........9999999999............
................................
................................
................................
................................
................................
`,
img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . c c c . 
. . . . c c c c c . . c c 1 c . 
. . . . c 1 1 c c . c c 1 1 c . 
. . . c c 1 c c . . c 1 1 1 c . 
. . . c 1 1 c c . . c 1 1 c c . 
. . . c 1 1 1 c c c c 1 1 c . . 
. . c c 1 1 1 1 1 1 1 1 1 c . . 
. . c 1 1 1 1 1 1 1 1 1 1 c . . 
. . c 1 1 1 1 1 1 1 1 1 1 c . . 
. . c 1 1 1 1 1 1 1 1 1 c c . . 
. . c 1 1 1 1 1 1 1 1 1 c . . . 
. . c 1 1 1 1 1 1 1 1 1 c . . . 
. . c 1 1 1 1 1 1 1 1 c c . . . 
. . c c 1 1 1 1 1 c c c . . . . 
. . . c c c b b b . . . . . . . 
`,
img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . e e e e f f f f f f f f f . 
. . e e e e f f f f f f f f f . 
. 1 e e e e 1 1 f f f f f f f . 
. 1 e e e e 1 1 1 1 1 1 1 1 f . 
. 1 e e e e 1 1 1 1 1 1 1 f f . 
. 1 e e e e f f f f f f f f f . 
. . e e e e f f f f f f f f f . 
. . e e e e f f f f f f f f f . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`,
img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . e e e 1 4 1 1 1 1 1 1 1 1 . 
. . e e e 1 4 1 1 1 1 1 1 1 1 . 
. . e e e 1 4 1 1 1 1 1 1 1 1 . 
. . e e e 1 4 1 1 1 1 1 1 1 1 . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];

const trashSpriteFunc = () => { 
    return trashSprites[Math.randomRange(0, trashSprites.length - 1)];
};

sprites.onCreated(SpriteKind.Trash, function (sprite) {
    trash = sprites.create(trashSpriteFunc(), SpriteKind.Projectile)
    trash.setPosition(randint(0, 190), randint(0, 190))
})

scene.onOverlapTile(SpriteKind.Player, assets.tile`dedTree`, function (sprite, location) {
    if (controller.A.isPressed()) {
        info.changeScoreBy(1)
        game.splash("Tree Restored Successfully!")
    }
})



function levelSwitch () {
    if (currentLevel == 1) {
        tiles.setCurrentTilemap(lvl1)
        currentLevel += 1
    } else if (currentLevel == 2) {
        if (info.score() >= 5) {
            tiles.setCurrentTilemap(lvl2)
            currentLevel += 1
        }
    }
}

sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (mainPlayer, trash) {
    if (controller.A.isPressed()) {
        info.changeScoreBy(1)
        sprites.destroy(trash)
    }
})

//local variables
let dedBush: Sprite = null
let trash: Sprite = null
let lvl2: tiles.TileMapData = null
let lvl1: tiles.TileMapData = null
let currentLevel = 0
let lvl0: Image = img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ff111111fff11111ff1111ffffffffffffffffffffffffffffffffffffffffff
ff1fffffff1ffffff1ffff1fffffffffffffffffffffffffffffffffffffffff
ff1fffffff1ffffff1ffff1fffffffffffffffffffffffffffffffffffffffff
ff1fffffff1ffffff1ffff1fffffffffffffffffffffffffffffffffffffffff
ff11111fff1ffffff1ffff1fffffffffffffffffffffffffffffffffffffffff
ff1fffffff1ffffff1ffff1fffffffffffffffffffffffffffffffffffffffff
ff1fffffff1ffffff1ffff1fffffffffffffffffffffffffffffffffffffffff
ff1fffffff1ffffff1ffff1fffffffffffffffffffffffffffffffffffffffff
ff111111fff11111ff1111ffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffff1111111fffffffffffff1ffffff1111f11111ff1111f1111fffffff
fffffffff1fffffffffffffffffff1fffff1ffff11fff1ff1ffff1fff1ffffff
fffffffff1fffffffffffffffffff1fffff1ffff11ffff1f1ffff1fff1ffffff
fffffffff1fffffffffffffffffff1fffff1ffff111111ff1ffff1111fffffff
fffffffff1ffffff1fffff11111ff1fffff1ffff11ffffff111ff11fffffffff
fffffffff11111fff1ff1f1ffff1f1fffff1ffff111fffff1ffff1f1ffffffff
fffffffff1ffffffff11ff1ffff1f1fffff1ffff11f1ffff1ffff1ff1fffffff
fffffffff1ffffffff11ff1ffff1f1fffff1ffff11ff11ff1ffff1fff1ffffff
fffffffff1ffffffff1f1f1ffff1f1fffff1ffff11ffff1f1111f1fff1ffffff
fffffffff1111111f1ffff11111ff11111ff1111f1ffffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff1ffff1ffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fff11111111111111111111111111111111111111111111111111111111111ff
fff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ff
fff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ff
fff1ff1111ff1111ff11111f11111f11111ffffffffff11111fffffffffff1ff
fff1ff1fff1f1fff1f1fffff1fffff1ffffffffffffff1fff1fffffffffff1ff
fff1ff1fff1f1fff1f1fffff1fffff1fffffffffffff11fff11ffffffffff1ff
fff1ff1fff1f1fff1f1fffff11111f1fffffffffffff1fffff1ffffffffff1ff
fff1ff1111ff1111ff111fffffff1f11111fffffffff1111111ffffffffff1ff
fff1ff1fffff11ffff1fffffffff1fffff1fffffffff1fffff1ffffffffff1ff
fff1ff1fffff1f1fff1fffffffff1fffff1fffffffff1fffff1ffffffffff1ff
fff1ff1fffff1ff1ff1fffff11111fffff1fffffffff1fffff1ffffffffff1ff
fff1ff1fffff1ff1ff11111fffffff11111ffffffffffffffffffffffffff1ff
fff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ff
fff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ff
fff11111111111111111111111111111111111111111111111111111111111ff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`
;

currentLevel = 1
lvl1 = tilemap`level4`
lvl2 = tilemap`level0`


info.setScore(0)


let mainPlayer = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)

let teleporter = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . 3 3 . . . . . . . . . 
    . . . . 3 3 . 3 3 . . . . . . . 
    . . . . 3 . . . 3 . . . . . . . 
    . . . . 3 3 3 3 3 . . . . . . . 
    . . . 3 3 3 3 3 3 3 3 . . . . . 
    . . 3 . 3 3 3 3 3 3 3 3 . . . . 
    . . . 3 3 3 3 3 3 3 3 3 . . . . 
    . . . 3 3 3 3 3 3 3 3 3 . . . . 
    . . . . 3 3 3 3 3 3 3 . . . . . 
    . . . . 3 3 3 3 3 3 3 . . . . . 
    . . . . . 3 3 3 . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Teleporter)

mainPlayer.setPosition(20, 280)
teleporter.setPosition(3969, 324)
console.log(mainPlayer)

let trash1 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
`, SpriteKind.Trash)
trash = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)
let trash2 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)
let trash3 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)
let trash4 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)
let trash5 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)
let trash6 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)
let trash7 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)
let trash8 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)
let trash9 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Trash)


controller.moveSprite(mainPlayer)
tiles.setCurrentTilemap(lvl1)
scene.cameraFollowSprite(mainPlayer)
